[package]
name = "maximal-lottery"
version = "0.1.1"
edition = "2024"
description = "A Rust library for computing maximal lotteries from preference profiles."
license = "MIT OR Apache-2.0"
repository = "https://github.com/buffbirb/maximal-lottery"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitvec = "1"
num-bigint = "0.5"
num-rational = { version = "0.4", features = ["num-bigint"] }
num-traits = "0.2"
thiserror = "2"
