name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        shell: devenv --quiet shell -- bash --noprofile --norc -e -o pipefail {0}

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          github_access_token: ${{ github.token }}

      - name: Use Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('devenv.lock', 'devenv.nix', 'devenv.yaml') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Install devenv
        shell: bash
        run: nix profile add nixpkgs#devenv

      - name: Build devenv shell
        shell: bash
        run: devenv --verbose shell -- true

      - name: Cache Rust crates
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cmd-format: devenv --quiet shell -- {0}

      - name: Run devenv tests
        shell: bash
        run: devenv --verbose test

      - name: Run Rust tests
        run: cargo test --all-features

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
